# Generated by Django 3.0.5 on 2023-01-31 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorare', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floorprice',
            name='floorPriceETH',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
        migrations.AlterField(
            model_name='scoutingresult',
            name='initialFloorPriceLimitedETH',
            field=models.DecimalField(decimal_places=4, max_digits=7),
        ),
    ]
