# Generated by Django 3.0.5 on 2023-02-01 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorare', '0002_auto_20230131_2037'),
    ]

    operations = [
        migrations.AddField(
            model_name='floorprice',
            name='not_for_sale',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scoutingresult',
            name='not_for_sale',
            field=models.BooleanField(default=False),
        ),
    ]
