# Generated by Django 3.0.5 on 2020-05-03 18:38

import allstar_teams.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllstarTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('founded_in', models.IntegerField(default=1900)),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('national_honors', models.IntegerField(default=0)),
                ('international_honors', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('is_manager', models.BooleanField(default=False)),
                ('illustration', models.ImageField(blank=True, upload_to=allstar_teams.models.get_upload_path)),
                ('games', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('honors', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.AllstarTeam')),
            ],
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('twitter', models.URLField(max_length=150)),
                ('instagram', models.URLField(max_length=150)),
                ('mail', models.EmailField(max_length=100)),
                ('webpage', models.URLField(max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country')),
            ],
        ),
        migrations.AddField(
            model_name='allstarteam',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country'),
        ),
        migrations.AddField(
            model_name='allstarteam',
            name='illustrated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Illustrator'),
        ),
    ]
