# Generated by Django 3.0.5 on 2021-02-05 21:56

import allstar_teams.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllstarTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50)),
                ('slug', models.SlugField(max_length=200)),
                ('founded_in', models.IntegerField(default=1900)),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
                ('national_honors', models.IntegerField(default=0)),
                ('international_honors', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('birth_date', models.DateField(default=datetime.date(1970, 10, 19))),
                ('death_date', models.DateField(blank=True, null=True)),
                ('club_years', models.CharField(blank=True, max_length=40, null=True)),
                ('slug', models.SlugField(max_length=200)),
                ('is_manager', models.BooleanField(default=False)),
                ('position', models.CharField(choices=[('1', 'Goalkeeper'), ('2', 'Defense'), ('3', 'Midfield'), ('4', 'Forward')], default='4', max_length=20)),
                ('illustration', models.ImageField(blank=True, upload_to=allstar_teams.models.get_upload_path)),
                ('games', models.IntegerField(default=0)),
                ('goals', models.IntegerField(default=0)),
                ('honors', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('team', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.AllstarTeam')),
            ],
            options={
                'ordering': ('position',),
            },
        ),
        migrations.CreateModel(
            name='Illustrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('twitter', models.URLField(blank=True, max_length=150)),
                ('instagram', models.URLField(blank=True, max_length=150)),
                ('mail', models.EmailField(blank=True, max_length=100)),
                ('webpage', models.URLField(blank=True, max_length=150)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('country', models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country')),
            ],
        ),
        migrations.AddField(
            model_name='allstarteam',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country'),
        ),
        migrations.AddField(
            model_name='allstarteam',
            name='illustrated_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Illustrator'),
        ),
        migrations.AddField(
            model_name='allstarteam',
            name='logo_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_illustrator_set', to='allstar_teams.Illustrator'),
        ),
    ]
