# Generated by Django 3.0.5 on 2021-02-08 19:59

import allstar_teams.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=allstar_teams.models.get_upload_path),
        ),
    ]
