# Generated by Django 3.0.5 on 2020-05-03 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='illustrator',
            name='country',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country'),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='instagram',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='mail',
            field=models.EmailField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='twitter',
            field=models.URLField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='illustrator',
            name='webpage',
            field=models.URLField(blank=True, max_length=150),
        ),
    ]
