# Generated by Django 3.0.5 on 2020-05-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0002_auto_20200503_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[(1, 'Goalkeeper'), (2, 'Defense'), (3, 'Midfield'), (4, 'Forward')], default=4, max_length=20),
        ),
    ]
