# Generated by Django 3.0.5 on 2021-02-12 20:16

import allstar_teams.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0002_player_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_image',
            field=models.ImageField(blank=True, upload_to='flags'),
        ),
        migrations.AddField(
            model_name='player',
            name='nationality',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country'),
        ),
        migrations.AddField(
            model_name='player',
            name='still_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=allstar_teams.models.get_upload_path_thumbnail),
        ),
    ]
