# Generated by Django 3.0.5 on 2021-02-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0003_auto_20210212_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='one_club_man',
            field=models.BooleanField(default=False),
        ),
    ]
