# Generated by Django 3.0.5 on 2020-05-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0003_player_position'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ('position',)},
        ),
        migrations.AddField(
            model_name='allstarteam',
            name='logo_by',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='logo_illustrator_set', to='allstar_teams.Illustrator'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('1', 'Goalkeeper'), ('2', 'Defense'), ('3', 'Midfield'), ('4', 'Forward')], default='4', max_length=20),
        ),
    ]
