# Generated by Django 3.0.5 on 2020-05-03 20:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0004_auto_20200503_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allstarteam',
            name='logo_by',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logo_illustrator_set', to='allstar_teams.Illustrator'),
        ),
    ]
