# Generated by Django 3.0.5 on 2021-03-14 12:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0004_player_one_club_man'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
                ('birth_date', models.DateField(default=datetime.date(1970, 10, 19))),
                ('death_date', models.DateField(blank=True, null=True)),
                ('available', models.BooleanField(default=True)),
                ('created', models.DateField(auto_now_add=True)),
                ('updated', models.DateField(auto_now=True)),
                ('nationality', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Country')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
