# Generated by Django 3.0.5 on 2021-03-14 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0006_auto_20210314_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='allstar_teams.Person'),
        ),
    ]
