# Generated by Django 3.0.5 on 2020-05-09 08:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0007_player_redbubble'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='birth_date',
            field=models.DateField(default=datetime.date(1970, 10, 19)),
        ),
        migrations.AddField(
            model_name='player',
            name='club_years',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='death_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
