# Generated by Django 3.0.5 on 2020-05-26 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200526_1937'),
        ('allstar_teams', '0008_auto_20200509_0830'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='products_available',
            field=models.ManyToManyField(to='shop.Product'),
        ),
    ]
