# Generated by Django 3.0.5 on 2020-05-31 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allstar_teams', '0009_player_products_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='allstarteam',
            options={'ordering': ('name',)},
        ),
    ]
